---
  
- name: net.ipv4.ip_forward = 1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
          
- name: Copy eth1
  copy:
    src: files/ifcfg-eth1.101
    dest: /etc/sysconfig/network-scripts/ifcfg-eth1.101
    owner: root
    group: root
    mode: '0755'
          
- name: restart network
  systemd:
    name: network
    state: restarted
    enabled: yes