---
- name: net.ipv4.ip_forward = 1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: copy bond0
  copy:
    src: files/{{ item }}
    dest: /etc/sysconfig/network-scripts/{{ item }}
    group: root
    owner: root
    mode: '0755'
  with_items:
    - "ifcfg-bond0"
    - "ifcfg-eth2"
    - "ifcfg-eth3"


- name: restart network
  systemd:
    name: network
    state: restarted
    enabled: yes